# Generated by Django 3.2.9 on 2021-11-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20211108_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
