# Generated by Django 3.2.9 on 2021-11-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_auto_20211108_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.ManyToManyField(to='memes.Tag'),
        ),
    ]
