# Generated by Django 3.2.6 on 2021-12-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
