# Generated by Django 3.2.6 on 2021-12-01 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_personalinformation_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('intro', models.CharField(blank=True, max_length=512, null=True)),
                ('imguploaded', models.IntegerField(null=True)),
                ('likes', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='personalinformation',
        ),
    ]
