# Generated by Django 3.2.6 on 2021-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20211202_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='memes/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
